### ISSUE TITLE
Device implemantation example 

### ISSUE THREAD

**Issue by yann77500** [ryan-summers/shared-bus-rtic#8]
Hello, I'am beginer in Rust, 

I don't understand how to implement a device.  I want to implement a I2C temperature sensor on I2C shared bus with RTIC.
Do you have an example to implement a device? Do you know where can I found an example please?

Thank  you by advance

**Comment by ryan-summers** [comment]
If you're interested in implementing the I2C portions specifically, I'd direct you to the [`awesome-embedded-rust`](https://github.com/rust-embedded/awesome-embedded-rust#driver-crates) list for some inspiration/examples. This crate only worries about sharing the implementation between multiple RTIC tasks and not the specifics of the device itself :)

**Comment by ryan-summers** [comment]
Also check out the embedded-hal docs on how to implement it:
https://docs.rs/embedded-hal/0.2.7/embedded_hal/blocking/i2c/index.html#device-driver-compatible-only-with-7-bit-addresses

In the example, this crate provides a `T` (generic type) that implements the e-h traits that you can provide to your driver.

**Comment by yann77500** [comment]
Thank you for your links and information. They will help me a lot
