### ISSUE TITLE
Update to embedded_hal-1.0.0 alpha

### ISSUE THREAD

**Issue by natrow** [ryan-summers/shared-bus-rtic#9]
Could this crate be updated to support the current `embedded_hal-1.0.0` alphas? There's also a new `SpiDevice` interface that would allow a safer implementation of a shared bus using dedicated CS pins.

**Comment by ryan-summers** [comment]
I'm happy to accept a PR for a new opt-in feature, but I do not want to adopt 1.0.0 of the e-h as the default until it is formally released.

**Comment by snorkman88** [comment]
Hi @natrow! Since e-h has already been released on Jan, 1st I think think you can open the PR now.

**Comment by ryan-summers** [comment]
Actually, with the advent of `embedded-hal` v1.0, this crate is no longer needed. `embedded-hal-bus` handles the synchronization mechanisms required. I even added in support for the RTIC mutexes directly:
* https://docs.rs/embedded-hal-bus/latest/embedded_hal_bus/i2c/struct.AtomicDevice.html
* https://docs.rs/embedded-hal-bus/latest/embedded_hal_bus/spi/struct.AtomicDevice.html

I should update the README to point to these newer tools.

**Comment by snorkman88** [comment]
Thanks for the heads-up and for your collaboration.
